kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocs-provider-server
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageconsumers
  verbs:
  - get
  - list
  - create
  - delete
  - update
- apiGroups:
  - ceph.rook.io
  resources:
  - cephclients
  verbs:
  - get
